### ISSUE TITLE
Question about picker

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#1034]
Hi guys, for my own education and for the purpose of mastering shoes I've started up a new project: [cordwainer](http://kcerb.github.io/cordwainer/).

The plan is to walk line by line through everything and write up a tutorial as I go. This is pretty analogous to how I learn new topics in the scientific research I do and I finally connected the dots that it might be a great way to get to know programming topics as well.

Anyways I'm sure I'll have lots of questions as things go on and here's my first one:

What's going on in [`shoes-picker'](https://github.com/shoes/shoes4/blob/master/shoes-core/lib/shoes/ui/picker.rb)? Reading through this, I can see that my first problem is misunderstanding how `Bundler` and `Gem` work.

Specifically:

1. We only require `bundler/setup` if there's a local `Gemfile`, and we seem to assume that they have `bundler` installed. The comment says that this "allows us to work properly running from source without finding gem-installed backends". I'm not to a tutorial (yet) on how the installation process works so I'm guessing that's an important gap in my knowledge, but my guess here is that the current directory is the directory of the shoes app we're running and we want to leave it open for the backend to be specified in the app's Gemfile?

2. It looks like after setting up Bundler we tell it to require the Gemfile or in other words bundle it (is that right)? I don't see how we're pointing `bundler` to that specific Gemfile.

3. I don't really understand how `Gem.find_files` is getting into each of the top-level files. I guess this question goes back to me not understanding what the current directory is here. It looks like it's searching for `shoes/any_directory/backend_generator.rb` but those `shoes` directories are a level-down from the top. Shouldn't it be `**/shoes/**/backend_generator.rb`? Why don't we need that first wild-card?

I feel like I get the general idea: pull in a local Gemfile if it exists, go get the only backend we support (`swt`), load it in, and then write out the `shoes-backend` executable over at top/bin so that we don't have to go through all this again.

It's just some of the specifics that I don't feel very confident about. 

Thanks for any time you can spend explaining stuff to me! :)

**Comment by jasonrclark** [comment]
Hey @KCErb, great questions! I wrote the picker stuff, so I'll try to get you some answers here.

1. The bits around Bundler are most important for supporting our local development. There might be more to do later on for gem installed copies of shoes (or benefits it brings to those), but for now just focus on the local dev aspect.

The key thing is what `bundler/setup` actually does, and that's setting up the load paths for your gems so that only things in your `Gemfile` are available. This is super important for local dev because our `Gemfile` forces everything to use the source copy rather than any gem installed copies of shoes.

We do kind of rely on Bundler being around, but if you're in a folder with a `Gemfile`, it's a pretty safe assumption that Bundler will be there for us.

2. Bundler will default to the `Gemfile` in your current working directory (or if you have an `ENV` value for `BUNDLE_GEMFILE`, that'll override where to look too). That's why the `Bundler.require` method doesn't actually have to call out the location.

You don't see this done a lot in things like Rails because the framework takes care of making that `Bundler.require` call for you, so it's all transparent.

3. `Gem.find_files` actually works against your load path (harkening back to 1. where our `bundler/setup` got all our paths set to only the gems we're interested in). This is actually provided by Rubygems rather than Bundler, and when it searches, it's looking in the `lib` folder for each of the gems in the load path. That's why we just look for `shoes/**/backend_generator.rb`.

Let me know if any of that doesn't make sense, or if there are further questions the answers bring up!

**Comment by KCErb** [comment]
Thanks Jason! That helps a ton :dancer: 

So as I'm tracing through the start-up process here I notice that a little after running `Picker` we run
something similar in [`shoes-swt/bin/shoes-swt`](https://github.com/shoes/shoes4/blob/master/shoes-swt/bin/shoes-swt`).

Specifically these lines:
```ruby
lib_directory = File.expand_path('../../lib', __FILE__)
$LOAD_PATH << lib_directory

if File.exists?("Gemfile")
  require "bundler/setup"
  Bundler.require
end
```
Am I right that this duplicates the work of `bundler` done in `Picker`, but is necessary because picker only gets run the first time?

Also am I right that these calls should do nothing on the first run since `require` will have already pulled that Gemfile in?

**Comment by jasonrclark** [comment]
Yep, you've got it right that it's the same thing repeated since the picker only runs the very first time.

Also you're spot on that the calls are harmless because 1) the load path is already set, and Bundler's smart enough to not goof with it more and 2) everything Bundler calls `require` on has already been required, and Ruby itself doesn't re-run files on subsequent `require` calls (if you want to force things to happen again, you've got to call `load` instead)

**Comment by KCErb** [comment]
OK great, thanks for confirming Jason. I love running into things I've seen in the textbooks out here in the wild (require vs load)!

With that my first [Cordwainer](http://kcerb.github.io/cordwainer/start/) lesson is done! I know you guys are super busy, but if you ever get bored or curious feel free to read through it and point out any mistakes that I've made. My goal is to at least have a great resource for myself and maybe even help someone else too.

**Comment by jasonrclark** [comment]
Haven't had a chance to read deeply yet, but that's a nice looking site @KCErb! Excited to read it. :book: :+1: :sparkles:
