### ISSUE TITLE
Slots content should be hidden when the slot is too small to display them

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1036]
Right now we paint elements no matter what the dimensions of a slot are:

``` ruby
Shoes.app do
  stack height: 0 do
    para 'Y U SEE ME?'
  end
end
```

Shoes 4
![screenshot from 2015-01-18 19 41 27](https://cloud.githubusercontent.com/assets/606517/5793604/5a13f464-9f4a-11e4-894a-786db9eff6e8.png)

Shoes 3.2
![screenshot from 2015-01-18 19 41 52](https://cloud.githubusercontent.com/assets/606517/5793607/628ea710-9f4a-11e4-9cb8-5c876ca2358f.png)

It gets more interesting if you have something big and a smaller slot:

``` ruby
Shoes.app do
  stack height: 25 do
    title 'Y U SEE ME?'
  end
end
```

Shoes 4:

![screenshot from 2015-01-18 19 45 21](https://cloud.githubusercontent.com/assets/606517/5793616/bd33be58-9f4a-11e4-8197-ab1943c706b3.png)

Shoes 3.2:

![screenshot from 2015-01-18 19 46 02](https://cloud.githubusercontent.com/assets/606517/5793617/c8d1a1bc-9f4a-11e4-9245-19bcc60a94f4.png)

I guess to correctly tackle this we'd need a backend for slots #905 

Discovered during lookign at #1021

**Comment by jasonrclark** [comment]
Good find. Curious what the behavior looks like for `button` and `rect` (which each use a bit different scheme from `TextBlock` which is it's own special :snowflake: )

**Comment by jasonrclark** [comment]
Double-checked and Shoes 3 does apply that behavior to the other element types I checked (rect and button). Shouldn't be too tough to apply to the painter-type elements (text and rect), but not sure how we'd accomplish that with SWT-widget-based things. Should be fun :grin:

**Comment by jasonrclark** [comment]
@KCErb won't be tromping on anything you're doing if I fiddle with the painting side of this, will I? Those won't be reliant at all on a `Slot` backend to function--they're done a whole different way.

**Comment by KCErb** [comment]
Definitely not, haven't started on this because I'm still on the colors part :P

**Comment by jasonrclark** [comment]
This is addressed for text and art elements by #1170, but work remains for the control elements. Punting that to a later release.

**Comment by jasonrclark** [comment]
So couldn't help myself entirely... I dug in and used the raw SWT shell to get a basic app demonstrating how I think we'd want to use composites to back up slots. This would provide the necessary machinery for concluding this PR, and the basis for implementing scrolling separately.

Sample app is available at https://gist.github.com/jasonrclark/bd2ac61b77f86bc04b45

Hope this didn't overlap with and/or steal something you were working on @KCErb... If you're not at a spot to pick any of this up, I'm happy to dig in as I've been getting a little more shoes-ing in, and this feel like one of the big remaining unimplemented bits between us and rc1.

Things I learned:

* We'll need a `ScrollableComposite` to scroll (duh), which then has `content`  we set via as another `Composite` (which holds the actual controls)
* When you tell SWT to let you absolutely position things by setting `layout = nil` on a composite, you'd better set where things are or you get blank screens everywhere!
* Text boxes swallow scrolling events, I presume since they can scroll themselves when you're moused over them. We may or may not want to deal with that, but it's kind of annoying. By the same token my web browser does it too, so ¯\_(ツ)_/¯
* There will be a lots of fun edges to figure out with this. It'll probably shift coordinate relationships, require new API's (although they should only be within the backend). Fitting the SWT API on this to what Shoes presents will probably have some rough spots too. An example--you can't change the styling on a composite once it's been created, so we can't easily set/unset scrollability on a slot. If we want the typical accessor to be available for `scroll` like other Shoes elements, we'll probably need to manually control the scrolling behavior, probably via an even handler.

A plan of attack:
* Don't do anything until pre5 is gone, but get started as soon after that as possible so we have a whole release cycle to shake things out.
* Update `Shoes::Swt::Slot` to actually create the nested composite structure described here. Create them with scrolling disabled (but may as well keep our changes to the main structure consolidated into one big shift)
* Update each of the `Shoes::Swt::*` elements that currently add themselves to the `@app.real`, and have them instead insert into their `parent.gui.real` (which should be a slot's backing composite after the first change).
* Fix any issues and :ship: This addresses #1036 and #905
* Plumb in to enable scrolling on the slots. This will likely work pretty well out of the box for the control-based elements.
* Fix all the painting based elements to take into account the scroll window for their containing slot. Shoes 3 does indeed obey the scrolling for contained art elements and text, and we should do.
* Fix any issues and :ship: again. This addresses part of #853
* Plumb in remaining scroll methods on slots, including `scroll_top`, `scroll_height` :scroll: Finishes remainder of #853
* Plumb in general on-scroll handling. That'll fix #150
* Profit :tada: 

:scroll: :scroll: :scroll:

**Comment by KCErb** [comment]
Woohoo! That sounds great! I haven't dug into this at all yet, but I'm excited to see what you come up with :dancer:

**Comment by jasonrclark** [comment]
Ugh, so bad news on this. It looks as though `Composite` in SWT doesn't allow for transparency at all, which makes it completely useless for our slots :sob: :crying_cat_face: 

Corroborating evidence: http://stackoverflow.com/questions/9542524/java-swt-transparent-composite-background and our own #79

#79 appears to have gotten closed because we figured out how to draw text and art elements, but it never actually addressed the controls. I have been completely unsuccessful in finding a way to get myself injected into the controls' drawing itself... major bummer.

I have some utterly hacky ideas around just positioning/hiding/showing things ourselves, but the behavior would not be at all smooth, which makes me super sad.

**Comment by PragTob** [comment]
Ugh that really sounds like a major downer... :-/ Isn't there another way? o_O

What hacks do you think about? I was thinking about storing the visible state of all elements and then restoring it once we show the slot again.

**Comment by jasonrclark** [comment]
Yeah, my first hack ideas is basically that @PragTob. It sucks because things won't disappear smoothly--they'll vanish when an edge (top or bottom) gets outside the range. Better than nothing, but not very nice.

I have a second even crazier idea that revolves around capturing the GC image for the parts we want to obscure and putting another SWT element (canvas maybe?) on top to obscure things. Strongly suspect that'll have problems, though I may try it as an exercise.
