### ISSUE TITLE
Still learning :)

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#1042]
Hi all,

I'm still working on learning more about our project and ran into a file that is pretty opaque to me :grimacing:.

My quandary is with our `gem` [tasks](https://github.com/shoes/shoes4/blob/master/tasks/gem.rb).

Looking around it seems like what happens in here is pretty standard, but I'm still not sure what that is.

For example the first thing we do is pull in bundler's `gem_tasks` which pulls in [`gem_helper`](https://github.com/bundler/bundler/blob/master/lib/bundler/gem_helper.rb) which then seems to try to load up available `gemspec`s (in this case probably just the `shoes.gemspec`).

From there I get the overall impression that a bunch of tasks get defined that are useful for releasing new versions of the gem but a few things are not 100% clear:

* Is this where we get `bundle install` from?
* What does `build` do?
* What does `release` do?

I don't see the actual code answering those questions in `gem.rb` so where is it? Surely it's defined in `bundler` but I don't see the connection. I cruised through the bundler docs a bit, but things are still a little fuzzy.

Any pointers would be appreciated!

**Comment by PragTob** [comment]
Hi @KCErb ! :)

Good to keep learning and asking :)

On to the answers:

* `bundle install` comes from bundler itself, it is a standard gem functionality that is used by almost every ruby project I dare say, it just looks for a `Gemfile` in the current directory and goes on and does its work. Nothing to do with the gem tasks.
* `build` builds the gem - not very helpful right? :) Build takes the gemspec (or `build:all` takes all gemspecs) and packages up the gems according to them, i.e. it produces a `.gem` file that contains all the files - so that file is an archive, zip or something. This file can then be distributed. You can try it! run `rake build:all` and it should create a bunch of files in the `pkg` directoy. You could then do `gem install pkg/gem_name.gem` to install the gem.
* Release, releases a new vesion of the gem to rubygems so people can specify the gem in their `Gemfile` or do `gem install shoes` to just download the gem. Basically this builds the gem (using the build task) and then pushes the resulting archive to the public rubygems.org server to enjoy. You won't have to use this task for now - these days @jasonrclark or I do the releases,

Did that make it clearer? :)
Tobi

**Comment by KCErb** [comment]
Hmm, yes it does! All very logical, but one thing I'm still unclear on is where does this all come from? Rake? Bundler? Gem? Ruby?

I sorta expected `task do` statements like we have in [this each block](https://github.com/shoes/shoes4/blob/master/tasks/gem.rb#L15-L37), but instead I just see naked `task "string"` statements like [this](https://github.com/shoes/shoes4/blob/master/tasks/gem.rb#L4). How does rake know to do the things you said?

**Comment by jasonrclark** [comment]
@PragTob is right on, although I'll add one extra little bit to it.

`install`, `build`, and `release` come from bundler, and are created by the require at https://github.com/shoes/shoes4/blob/master/tasks/gem.rb#L1

Each gem we have (`shoes`, `shoes-core`, etc.) has those three tasks directly from bundler.

That `task do` block set up our own custom tasks for building each of the gems from the root of the project (effectively in the `shoes` gem). So creates the tasks for `rake build:shoes-core`, and a `rake build:all` that knows about our dependencies and does the whole thing in a batch.

Hope that helps.

**Comment by KCErb** [comment]
OK, I think I see it now. 

So could I say that
* `task 'build:all'` is initializing the `build:all` task for scoping reasons and then in the `each` loop we add tasks like `build:shoes-core` to `build:all`?

* The line where we say `task "build:shoes"   => "build"` we're saying when `build:shoes` gets called, then call the `build` method that Bundler gave us which takes the local gemspec (shoes.gemspec) and packages up shoes?

If I understand correctly, then the result of this file is that a call to any of the core methods (`install:all`, `build:all`, `uninstall:all` or `release:all`) will result in a chain like this (using build as an example):

```
build:all ->
  - build:shoes
    - build
  -build:shoes-core
    - cd lib/shoes-core && rake build
  -build:shoes-package
    - cd  lib/shoes-package && rake build    
  -build:shoes-swt
    - cd lib/shoes-swt && rake build
```

If that's right then this makes sense to me and thanks!

If that's wrong . . . let me know :)

**Comment by jasonrclark** [comment]
Yep, that's all correct.

**Comment by wasnotrice** [comment]
@KCErb Since I think from reading the article you shared recently that you really want to understand every detail of the process, it might be worth noting that here:

> The line where we say task "build:shoes" => "build" we're saying when build:shoes gets called, then call the build method that Bundler gave us which takes the local gemspec (shoes.gemspec) and packages up shoes?

when we say `"build:shoes" => "build"`, what we're really saying is that when `build:shoes` gets _invoked_ (in Rake's terminology), then *before you execute the `build:shoes` task*, make sure that the `build` task has been run. Then run `build:shoes`. 

Minor point, in a way, but if you're trying to follow all of the steps in the build process, it'll help. A great way to illustrate this is to run rake with the `--trace` option:

```
$ rake build:all --trace
** Invoke build:all (first_time)
** Invoke build:shoes-core (first_time)
** Execute build:shoes-core
cd ./shoes-core && rake build
shoes-core 4.0.0.pre3 built to pkg/shoes-core-4.0.0.pre3.gem.
** Invoke build:shoes-package (first_time)
** Execute build:shoes-package
cd ./shoes-package && rake build
shoes-package 4.0.0.pre3 built to pkg/shoes-package-4.0.0.pre3.gem.
** Invoke build:shoes-swt (first_time)
** Execute build:shoes-swt
cd ./shoes-swt && rake build
shoes-swt 4.0.0.pre3 built to pkg/shoes-swt-4.0.0.pre3.gem.
** Invoke build:shoes (first_time)
** Invoke build (first_time)
** Execute build
shoes 4.0.0.pre3 built to pkg/shoes-4.0.0.pre3.gem.
** Execute build:shoes
** Execute build:all
```

See how rake invokes a task, then executes all of its dependencies in the order they were assigned, then executes the original task? In particular, see how the `build` task only happens _after_ the other gems are built? That makes sense, of course, because the shoes depends on all of the other gems. And that's the Rake magic :)

**Comment by KCErb** [comment]
Thanks everyone for the excellent help and explanations! And thanks @wasnotrice for explaining what `=>` is really doing. I really want those articles I'm writing to be as accurate as possible so I love getting the feedback.
:heart: :heart: :heart:
