### ISSUE TITLE
MENUBAR widget for shoes 4 ?

### ISSUE THREAD

**Issue by systemaker** [shoes/shoes4#1130]
Hello,
i am newbie so i wonder like the others why there is still no menubar widget in shoes ?
even after 10 years,  the menubar is still a must-have in Gui widgets and even windows 8 had to bring back the start menubar ^^

**Comment by jasonrclark** [comment]
Hey @systemaker!
The short answer on menus is that Shoes 4 is still working towards being fully feature compatible with the original Shoes. Since the original Shoes didn't have a menu option, it hasn't even been on our radar.

That said, I think your point that it's a super common UI widget is true. I'm going to mark this for our 4.1 release (when we'll start doing new things that weren't in the original Shoes).

If you or anyone else wants to pick it up sooner than that, would be really glad to help out with that. For our SWT-backed implementation, I'm betting something revolving around [org.eclipse.swt.widgets.Menu](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fswt%2Fwidgets%2FMenu.html) would be the place to start.

**Comment by PragTob** [comment]
Is this the same as #219 or something different? :)

**Comment by systemaker** [comment]
Thanks for your future contribution in a cool world :)
