### ISSUE TITLE
Question about Delegation between App and InternalApp

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#1140]
Hi all,

I'm back to reading through the code and trying to learn / understand it more carefully. I've come across a couple of questions.

I'm looking at how `App` and `InternalApp` work together to make a clean execution context. I'm wondering how the following app works.

```ruby
Shoes.app do
  width = 50
  rect 0, 0, width
  alert width
  alert self.width
end
```

This behaves as I expect it to, (alerting 50, then 600), but I thought calls like `width` always had the implied receiver: `self` so the idea that `width` and `self.width` could return different values seems strange. I see why we do this, and that it's good, but I don't understand how `def_delegators` accomplishes the trick.

**Comment by jasonrclark** [comment]
Excited to hear you're digging back in a bit! I've had a crazy few weeks with work that have left me less itching for programming at home, but I'll be back to Shoes soon, I'm sure :grinning:

There's definitely a lot of interesting stuff happening between `App` and `InternalApp`, but I don't think what you're observing here actually involves the delegation.

If we only consider method names, then `width` is the same as `self.width`. But before even considering an identifier as a method, Ruby tries to see if it's a local.

A little pry session to demonstrate what I mean (and what's happening in your app there):

```
[1] pry(main)> def m
[1] pry(main)*   puts "yo"
[1] pry(main)* end
=> :m
[2] pry(main)> m = 10
=> 10
[3] pry(main)> m
=> 10
[4] pry(main)> self.m
yo
=> nil
```

So the local variable `width` takes precendence in Ruby's lookups over the method `width` (which is defined on `Shoes::App`, which eventually delegates to `Shoes::InternalApp`).

Closing out since I think that covers it, but feel free to reopen (or just comment even) if there's more to discuss!

**Comment by KCErb** [comment]
Ah I see. Good to know. Glad to get any attention from you and hoping @PragTob is doing alright.

**Comment by PragTob** [comment]
Hey folks, I'm all good was just a busy weekend and week :) Appreciate the concern, I'm back working for the past two weeks and generally feeling better if not good. I played a bit with crystal but hope to get back to my beloved shoes this weekend, if only for a bit :)

Also, work for JRubyConf.EU and eurucamp is heating up, so that bites off time :)
