### ISSUE TITLE
shoes3 to shoes4 items require changing

### ISSUE THREAD

**Issue by thebenjy** [shoes/shoes4#1200]
shoes3 app all works fine. using shoes4 had to change the following

**didn't recognised**

```
   self.start do
        # do scrreen refresh
   end
```

**crashed the app if button pressed**

```
  $log_window has be initiated as a para ''
  button "Copy Log Content" do
     app.clipboard = $log_window.text unless $log_window.nil?
  end
```

**doing a widget update (list_box) within the change event**
in shoes3 the box always selected an item, in shoes4 it was blank - probably not good code anyhow so needed to change

```
  $ini_file_lb.change do
    # do something that included
    $ini_file_lb.items = <new list>
  end
```

**layout changes for stacks**
fonts, gaps etc were all smaller under shoes4
had a number of stacks which had a margin, drawing the objects
within the stack ended up displaying outside the stack 

**basic app**
under shoes 3 all widgets contained within the white rectangle of the stack
shoes4 the buttons displayed on the border/outside the bottom of the rectangle

```
   stack :width => "98%", margin: 10 do
      background white
      flow do
        image "1.png", :margin => 0
        title "Environment"
        flow do
             $env_r_staging = radio :server, checked: true
             para "Staging (Test)       "
             $env_r_production = radio :server
             para "Production"
           end
             para "" # added in shoes 4 to make sure stack white rectangle big enough
      end #flow
    end # stack
```

**Comment by PragTob** [comment]
Thank you, we'll investigate those individually. I've never seen `self.start` - you never learn enough about the old shoes :D 

We can try to get text sizes and margins closer to shoes3, which we should, but they'll never be the same.

**Comment by ccoupe** [comment]
In Shoes3 self.start{} probably gets to app.start{}. It's a block to run after the all the widgets in partial ly evaluated Shoes.app are on screen and able to accept state settings. Some folks use a timer(0) block to do the final gui setup. It's something of a standard practice when setting the check or radio states after the Shoes.app block is loaded/evaluated but the event loop isn't really running so there's not widget to change. Very much a Shoes huh! thing that bites everyone.

**Comment by thebenjy** [comment]
i actually prefer smaller text sizes but prob acknowledge a clean migration is required. maybe a switch to "update look n feel".
@ccoupe timer(0) seems fair approach. perhaps an alias to handle migrations?

**Comment by jasonrclark** [comment]
Hey @thebenjy! I know it's been a long time, so you might not be interested still, but I've been working ahead on the various things you reported here. Appreciate the clear bug reports.

On the next to last, I've started up the [beginnings of a compatibility list for Shoes 3](https://github.com/shoes/shoes4/wiki/Compatibility-with-Shoes-3). I'll definitely look at extending this into more of a migration guide closer to the 4.0 release, and the look-n-feel you point out will be a key element about that.

On the final sample, I've had trouble duplicating your result, but I wonder if it's because I don't have the same `1.png` that it's referencing. In my Shoes 4 version when I popped some random image in, I see that the radio is very close to the left edge of the white background, so much so that the control highlighting slips over the edge, but nothing overlapping the bottom.

Here's a snapshot (with yellow background added in the remainder of the frame to help my eyes sort it out)

![image](https://cloud.githubusercontent.com/assets/130504/23596260/af61d89e-01dd-11e7-957d-f52c86ecedaf.png)

Thanks again for all the footwork, and sorry again that it took so long to get to them!
