### ISSUE TITLE
Shoes freezes trying to get information from serial port

### ISSUE THREAD

**Issue by snowe2010** [shoes/shoes4#1215]
I know that the last version of Shoes required you build your own gems into the executable if it had c extensions. Is that still the case with this version? I am trying to use Shoes to set up a connection to an Arduino over serial. I've got this: 

```ruby
require 'rubyserial'
require 'shoes'

Shoes.app do
  serialport = Serial.new 'COM4', 9600

  button 'Is ready?' do
      puts "serial port was #{serialport.gets}"
  end
end
```

but the application freezes as soon as I press the button.

**Comment by ccoupe** [comment]
If you are willing to install Shoes 3.3.x and modify your script to
```ruby
Shoes.setup do
  gem 'rubyserial'
end
require 'rubyserial'
Shoes.app do
  serialport = Serial.new 'COM4', 9600

  button 'Is ready?' do
      puts "serial port was #{serialport.gets}"
  end
end
``` 
It just might work for you because that gem has pre-built binaries for Windows. I don't have any com ports on my Win 7 VM  but it's dieing inside the Serial.new so that would be expected. File a bug report/issue at https://github.com/Shoes3/shoes3/issues . As the Shoes 3.3 maintainer and Raspberry PI owner this usage of Shoes is important to me.

I'll let others weigh in on Shoes4 ability to handle ffi and Shoes.setup

**Comment by PragTob** [comment]
Hi there,

shoes 4 should handle FFI gems just fine. I have a shoes application that connects to my sphero and I think that also uses serialport underneath.

The thing here might be that `serialport.gets` blocks the main thread of Shoes which does drawing and almost anything else. You could do:

```ruby
Thread.new do
  puts "serial port was #{serialport.gets}"
end
```

to see if that's the case, should work :)

**Comment by snowe2010** [comment]
fantastic! That was exactly it, a new Thread works perfectly. I don't know why I didn't think of that.

**Comment by PragTob** [comment]
:) glad to help :+1:
