### ISSUE TITLE
It's JRuby only

### ISSUE THREAD

**Issue by sixtyfive** [shoes/shoes4#1235]
Makes me very sad :disappointed:

**Comment by ccoupe** [comment]
Why Sad? If you want MRI Ruby, then use [Shoes 3.3](https://github.com/Shoes3/shoes3) which is actively maintained --(by me and a few others) you can download it from [here](http://shoesrb.com/downloads/).  I see don't see sad. You have options. Enjoy them.

**Comment by sixtyfive** [comment]
Well, I am using 3.3. But at some point it's going to be superseded by 4.0 and cease to be maintained, correct?

**Comment by ccoupe** [comment]
Not likely to merge.  3.3 does some C level things  that would be hard to do with jRuby and 3.3 is drifting towards a more native app developer focus and less of a beginner/educational tool as _why intended Shoes to be. Shoes4 is more pure to the __why vision_ and Shoes 3.3  will wander into MRI/C/Gtk/Cocoa strange places as requested that may not be not (easily) cross platform,

**Comment by sixtyfive** [comment]
I see, so things will be completely different at some point and it seems I'm part of the more-native-focus faction. Sorry for bothering you with this non-issue and thanks for _two_ great softwares then! :smiley:

**Comment by ccoupe** [comment]
They are different now! I could list at least 10 features and many more bug differences between 3.3 and Shoes 4. Simple scripts will work in both. Thats good. Not so simple scripts will fail  if they violate some assumption the user has about what Shoes is. There's an endless supply of those assumptions.

jRuby is a rational choice for Shoes4. MRI/Gtk/Cocoa is a rational choice for 3.3 and there's an infinite range of numbers between 3.3 and 4.  I reopened the issue because others may want to read or comment.

**Comment by PragTob** [comment]
Seems resolved and @ccoupe explained it fairly well, so thanks :)

One more thing, the default backend for now is JRuby + SWT. Shoes 4 is architected in a way that allows swapping out that backend for anything, we have proof of concepts for CRuby + Qt, Opal + atom-shell (or whatever the new fancy name is) etc. What those, and this project lack right now is the time and power to work on them to push them forward. Sadly. :(
