### ISSUE TITLE
Redrawing aspect - why are we painting elements without a gui?

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#1289]
Right now (as of #1281) we need this piece of code in the redrawing aspect:

      def redraw_target(element)
        if element.gui
          element.gui.redraw_target
        else
          element
        end
      end

The reason seems to be that redrawing sometimes triggers during initialization... which it probably shouldn't, only after everything is setup correctly. My thought/fear is that some methods which trigger a redraw are already called before initialization is done.

> So the actual reason is that we occasionally trigger the redrawing during initialization of some elements (Image in particular), so we'll get here before the gui is actually set in a class. Haven't dug too deeply on why we get that redraw at this point, since this seemed relatively benign.

Would be cool to investigate this and maybe get rid off that if. If it'd be a huge change then we're maybe ok without it as long as this doesn't cause any other problems :)

**Comment by jasonrclark** [comment]
Dug into this and the reason we have that issue is that `Shoes::Swt::Image#initialize` ends up calling through to `create_image` which happens to be tagged (appropriately it seems?) for redrawing. Unfortunately, while `Shoes::Swt::Image#initialize` is running is before we've set the backend on the DSL, hence why `element.gui` is nil at that point in time.

I've tried two approaches to fixing this. The first was to separate out the actual image loading into an `after_initialize` at which point the `gui` has been set. The second was to change the method we're triggering redraws from to a different, higher-level method and use a lower-level non-redrawing method from `initialize`.

Both of them unfortunately had drastic failures in either the specs or the samples, to the point of making me lose my appetite for changing it just to avoid the conditional. I've made an explanatory comment in dd7114f998ffcefa77a635f00790e627fa58d171, and gonna roll with that. Good Enough ™.
