### ISSUE TITLE
shoes fails to recognize my JRuby installation

### ISSUE THREAD

**Issue by bolandross** [shoes/shoes4#1432]
Hey folks,

since I got curious, I wanted to try on some shoes!

Installed via `gem install shoes --pre`

and then calling `shoes` gives me the following:

```
Selecting shoes-swt backend to use. This is a one-time operation.

*******************************************************************************
The shoes-swt backend requires a 9.X version of JRuby.

You are running the following Ruby instead:

  ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]

Please download JRuby from http://jruby.org (or your favorite Ruby version
manager), then check our https://github.com/shoes/shoes4#installing-shoes-4 to
get Shoes installed.

Sorry for the inconvenience!
*******************************************************************************
```

Running` jruby --version` tells me though:

`jruby 9.1.8.0 (2.3.1) 2017-03-06 90fc7ab Java HotSpot(TM) 64-Bit Server VM 25.121-b13 on 1.8.0_121-b13 +jit [darwin-x86_64]`

I am riding OS X El Capitan Version 10.11.6

Any ideas what I have to do?

Thanks in advance!

**Comment by jasonrclark** [comment]
Hey @bolandross! How are you managing your Ruby versions, and how did you get JRuby installed?

It looks as though you're current Ruby when you gem installed was MRI 2.4.1. You're probably wanting to use a Ruby version manager (rbenv, RVM, or chruby) and make sure that you've selected JRuby before doing the gem installation.

**Comment by bolandross** [comment]
Hey and thanks for the superfast response!

It was my fault, since I installed the gems with Ruby instead of JRuby (as you said)

On my machine, JRuby was installed via homebrew. For me in command line, `ruby` points to MRI 2.4.1 and `jruby`points to jruby 9.1.8.0.

With this new knowledge, I managed to install the shoes4 gem successfully by entering
`jruby -S gem install shoes --pre`

Though, when running `jruby -S shoes` for the first time, I receive this error:
```
SyntaxError: /usr/local/Cellar/jruby/9.1.8.0/libexec/bin/shoes:9: `$(' is not allowed as a global variable name
  NEXT_DIR=$(dirname $1)
```
Any ideas on how to proceed from here?

**Comment by jasonrclark** [comment]
Hmm, that's interesting. You can work around that by running `jruby -S shoes-swt`  instead of `jruby -S shoes` (all the arguments and things work the same). You may find it necessary to pass `-J-XstartOnFirstThread` to `jruby` in this case (or I've set it in my env via `export JRUBY_OPTS=-J-XstartOnFirstThread`). More on options around this [in the README](https://github.com/shoes/shoes4#running-a-shoes-app).

Why's this happen? Well, [to avoid starting up JRuby multiple times](https://github.com/shoes/shoes4/blob/master/ext/install/Rakefile#L5-L17), the `shoes` executable is actually a bash script. With a Ruby version manager, that script is right in the path, so you can just call it. But with JRuby installed on the side like that, trying to do `jruby -S` actually tries to interpret that bash script as Ruby, which fails. `shoes-swt` is the "real" Ruby executable that we eventually invoke, so `jruby` can run it.

Another alternative would be to make sure that `/usr/local/Cellar/jruby/9.1.8.0/libexec/bin` is in your path, and then you should be able to just call `shoes`.

I'll continue to mull this over and leave it open for a while and see if I can find a better option. I'd love for folks to not have to use a version manager to get the right behavior.

**Comment by bolandross** [comment]
Thank you, that worked for me! 😅👍🏼
