### ISSUE TITLE
Contents off all apps escape the window: elementary OS 0.4.1

### ISSUE THREAD

**Issue by worldofpeace** [shoes/shoes4#1506]
![image](https://user-images.githubusercontent.com/28888242/32357716-b417ae4e-c015-11e7-94a0-b942db790631.png)

**Comment by jasonrclark** [comment]
That’s super weird! What OS, window manager and Java version are you running?

**Comment by worldofpeace** [comment]
OS: elementary OS 0.4.1
Window Manager: gala(fork of mutter)
Java Version: Oracle JDK 8

**Comment by jasonrclark** [comment]
Cool, thanks for the info @worldofpeace! It may take me a while to get set up to try and duplicate that--only bits of Shoes time in the evenings here and there :)

I'm assuming from the title that you've tested some samples and gotten this result there too. In the app shown above, are you setting any height/width on the app explicitly like the following, or just using the default sizes?

```ruby
Shoes.app width: 200 do
  # ...
end
``1

**Comment by worldofpeace** [comment]
Hi @jasonrclark! I've tested all the samples and seen this weirdness. This app did have width and height specified but I removed it and it does that same thing. 

I have some time this evening to spin up a vm and try to reproduce this. :)

**Comment by worldofpeace** [comment]
I can reproduce this on elementary OS 0.4.1 consistently. Don't know _why though :)

**Comment by worldofpeace** [comment]
Any thoughts into what I should look into to? This is very os specific and it's using a fork of libmutter. Maybe a window manager problem? I saw someone using an older version of elementary OS with shoes3/shoes4. Here's the  [video.](https://www.youtube.com/watch?v=Kzo2JPdFv9Q) I don't see this issue in this video so maybe this was some changes done recently in eOS that broke it :(.

**Comment by jasonrclark** [comment]
Hey @worldofpeace! Definitely wonder about the window manager, but have done little testing myself outside of Unity on Ubuntu. I know @PragTob used to run Mint as well.

Two things you could do to help out.

First, I've created a minimal SWT example repo at https://github.com/jasonrclark/raw-swt that you could clone and run `app.rb` in and see what the results are. If that shows similar things, then it means it's likely something affecting the SWT framework we're using, not something we've done wrong in Shoes on top of it.

Second, if you could drop any instructions/links/pointers on the VM setup that you're using, that'd save me a ton of time when I'm able to get to looking closer.

Thanks for checking back in!

**Comment by worldofpeace** [comment]
Music too my ears! That's some cool problem isolation you did there because I was wondering about SWT in the back of my head

I've ran it and...
![image](https://user-images.githubusercontent.com/28888242/32477502-b4ed4f6a-c34c-11e7-890f-da146693e966.png)

It looks fine

So shoes maybe...

I could upload a virtualbox application image somewhere with the OS cleanly installed on it if you like. :)

**Comment by worldofpeace** [comment]
How's it coming?

**Comment by jasonrclark** [comment]
Hey @worldofpeace! Thanks for the ova and instructions.

At the moment, I'm actually getting set to speak at RubyConf next week (about Shoes!) and as such I'm getting a new release of Shoes out the door to go with it. Reality as this point is I probably won't get to look closely at this until after next week, say 11/20 or so.

Appreciate your patience and the footwork up front. Once other stuff settles down this is the first issue on my pile to investigate.

**Comment by worldofpeace** [comment]
Hi @jasonrclark! I love Shoes go talk about it! 

Go spread the good word :+1:

**Comment by worldofpeace** [comment]
How have things settled? :)

**Comment by jasonrclark** [comment]
Finally got down to downloading the image tonight and looks like I've got it figured out (at least enough to work around it), thank you @worldofpeace!

Boils down to problems running with SWT against GTK 3 instead of GTK 2. I haven't gotten into the root causes there, but some of the dimension calculations seem to be very, very wrong when on 3 vs 2...

[We've actually hit problems like this before](https://github.com/shoes/shoes4/pull/880#issuecomment-55183970), and in those cases, we were able to fall back to GTK 2 by setting the ENV variable `SWT_GTK3=0`. That comment even alludes to us setting it by default in our startup scripts... which we didn't do, but [I'm PR'ing now!](https://github.com/shoes/shoes4/pull/1523)

If you want to test @worldofpeace, you'll need to grab the source, do the [usual setup dance if you haven't run Shoes from source before](https://github.com/shoes/shoes4#installing-shoes-4-from-github), and then run on the `gtk-2` branch. Simple `bin/shoes` commands should get you the right thing then (and the wrong thing when on `master`).

**Comment by worldofpeace** [comment]
Glad to see you hacking @jasonrclark . Haha those dimension calculations are indeed, very, very, wrong.

But you've brought my shoes to the tailor and they now fit properly.

<img src="https://user-images.githubusercontent.com/28888242/33306822-0edd9142-d3e2-11e7-9c56-5717b0fdedee.png" alt="maybe..." title="maybe..."/>


Excellent! 
But I don't think you should avoid gtk3 further.
