### ISSUE TITLE
cursor size in edit_line

### ISSUE THREAD

**Issue by ashbb** [shoes/shoes4#260]
Refer to [this discussion](https://github.com/shoes/shoes4/commit/a7ecb047bcb208fff674a4018632eb5d2e186d44). Let's continue where we left off.

**Comment by jasonrclark** [comment]
Looking this over, it doesn't appear like Shoes 3 or 4 supports changing the font and font size on edit boxes (or at least it didn't respond to the changes I tried to make). If that's the case, there won't be a lot of variation in the sizing, which seems to make this less of an issue. I'm inclined to close and move on. Any objections?

**Comment by PragTob** [comment]
I believe it is a bit more about it looking good in the input box size wise, as shown in this [comment](https://github.com/shoes/shoes4/commit/a7ecb047bcb208fff674a4018632eb5d2e186d44#commitcomment-3244444).

**Comment by jasonrclark** [comment]
Yeah, I see what you mean @PragTob, I just thought it would be more pronounced with different sizes.

Going to see if I can coerce SWT into placing that cursor more nicely on Mac. The Linux screenshot looked properly centered on the caret, though, which worries me about any crazy stuff to try and fiddle with it making things worse on other platforms. We shall see!

**Comment by jasonrclark** [comment]
So spent some time digging, and I can't coerce the sizing of the caret to change in a meaningful and controllable way.

I see two options 1) live with it and close this out, or 2) alter the default on Mac to 24 instead of 28 for an unmodified textbox.

Thoughts @PragTob or anyone else who cares? We don't do a lot of these sort of platform specific fiddles, which leans me toward 1) but 2) is easy enough to do (and we do have other platform specific stuff headed in like #710 so maybe a way of handling that nicely would be good to investigate).

**Comment by PragTob** [comment]
I'd sort of lean towards 1.) and reopen/revisit if anyone takes issue with it again. Agreed? :)

**Comment by KCErb** [comment]
Sounds good to me

**Comment by jasonrclark** [comment]
All right, closing out. Thanks @PragTob @KCErb !
