### ISSUE TITLE
Why is standalone app package  so big?  Does it reduce fat in future?

### ISSUE THREAD

**Issue by janckerchen** [shoes/shoes4#473]
I just package  simple-sound.rb and get standalone app for mac with hug size >200M!

JDK is about 100M,  I think JRE is enough for end user.

Is there space for optimize?

**Comment by MichaelDimmitt** [comment]
I know this shouldn't be here but I wanted to mention it. @PragTob
Wrote a nifty script. My install uninstall package is fairly simple. So I removed all of the gems that I could from the jar file. Shrunk the Jar file down from 63mb to 35mb with program retaining functionality. Now I'll take a look at shoes/furoshiki because the script I wrote is a bandaid. For my specific small project. https://github.com/MichaelDimmitt/aerial_desktop_with_shoes/blob/fb4fa115d0825db72e4df03b2a6d3d5bb9df948c/script.sh

**Comment by jasonrclark** [comment]
There's definitely more room to trim, but I'm comfortable with the 65MB that we've gotten it down to for now (i.e. probably through the 4.0 release). Might be worth at least cutting out the biggest files (i.e. the duplicate jruby jars we slurp in because of our gem dependencies), but I'm willing to let that ride to focus on other aspects.
