### ISSUE TITLE
Packaged App on Mavericks Fails to open

### ISSUE THREAD

**Issue by the-undefined** [shoes/shoes4#477]
Hello,

I've managed to package up a simple application following the README instructions:

``` rb
# app.rb
Shoes.app do
  stack do
    para "some text"
  end
end
```

But opening the packaged app (`open pkg/app.app`) results in an application crash, the output I have stored in [a gist](https://gist.github.com/the-undefined/7435080).

I'm using:
- Mac OSX 10.9 (Mavericks)
- jruby-1.7.6
- shoes4 checked out from master (@ 2013-11-06 74ebd22)

Let me know if you need any further details or testing.
 :smile: 

Thanks!

**Comment by PragTob** [comment]
Please note shoes/furoshiki#16 were another possible cause for this is suggested, e.g. things in the jar app template.

**Comment by jasonrclark** [comment]
So this has been hanging out a long time and I'm unable to duplicate it on Mac OS X 10.11.6, running under JRuby `jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.102-b14 on 1.8.0_102-b14 [darwin-x86_64]`

It looks like there's some additional details over in the [related furoshiki issue](https://github.com/shoes/furoshiki/issues/16) that'd be worth me reviewing, but otherwise I'm likely to close this unless someone's got a more recent duplicating case.

**Comment by jasonrclark** [comment]
On further reading, that original furoshiki issue was dealt with in a later PR, although there were different issues later that'll bear investigation.

Closing this out as unable to dup with latest versions. Happy to reopen, or take bugs for anyone who can see the same thing happening still!
