### ISSUE TITLE
samples/simple-form.rb doesn't work properly (background image placement + Shoes.p)

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#526]
- background doesn't position images properly
- `Shoes.p` doesn't do anything

![image](https://f.cloud.github.com/assets/908/1825768/95222da0-71d3-11e3-831a-8567dc1bebb2.png)

**Comment by jasonrclark** [comment]
So I'm also seeing the `Shoes.p` on the console, so that's good.

On the offset, I started digging into this a little, and decided to monkey with the image that we're actually using on the right background to put a border around it in the image itself. I hoped this would give me some insight into what was happening, and it has.

So the new right image I was using looks like this:

![image](https://cloud.githubusercontent.com/assets/130504/5890409/b2260c38-a40d-11e4-8916-2fec6abaebb4.png)

But when I run the app, surprisingly I see this:

![image](https://cloud.githubusercontent.com/assets/130504/5890410/c67f93fc-a40d-11e4-9dc2-d7372d570739.png)

When I resize, it appears almost as if the background image is being tiled from the left edge of the screen, and the background is just showing us the slice of it where it's positioned. Don't really understand how that's getting painted yet, and probably won't tonight, but thought I'd jot this down in case someone who knows more about that understands why I'd be seeing that effect.

**Comment by PragTob** [comment]
Yeah I also had the impression that this was happening... I guess the solution should/could be to just paint that background once if it gets positioned like this (it would be like a normal image in the background then)

**Comment by PragTob** [comment]
On this again and I use my new patent method: "Change values until you find the value that changes what you like"tm

No, not really but it's the rect painter and it might simply be that we skip background positioning in the positioning code... investigating!

**Comment by jasonrclark** [comment]
Made a PR against this @PragTob... hope you didn't have too much work in flight, and happy to recant on mine if you have better thoughts. What I put up isn't quite ready for merging, but I think it might be the best way to handle how SWT's pattern falls short of what we want to achieve here.

**Comment by PragTob** [comment]
Was in the research phase, no code written yet :)
