### ISSUE TITLE
background color hides text_block

### ISSUE THREAD

**Issue by plexus** [shoes/shoes4#599]
When setting the background color after creating a text block, the text block gets hidden.

```ruby
Shoes.app { banner '0:00' ; background '#ff0000' }
```
I'm on Linux. Same behavior on current Shoes 4 and Red Shoes. Green shoes not affected. The reverse works fine:

```ruby
Shoes.app { background '#ff0000' ;  banner '0:00'  }
```

**Comment by jasonrclark** [comment]
Plan here is to maintain the overlapping behavior since it's consistent with Shoes 3. A background/foreground painting divide would be nice, but is kind of a breaking change better left for later release.

However, there is an inconsistency in behavior around positioning--the background in Shoes 4 picks up the current delta in the y, when it should just take up the parent container. Pics or it didn't happen:

**Shoes 3**
![image](https://cloud.githubusercontent.com/assets/130504/9021910/81dabb34-3812-11e5-899c-2871676dc7b2.png)

**Shoes 4**
![image](https://cloud.githubusercontent.com/assets/130504/9021911/8accbecc-3812-11e5-8920-2c72c64032a3.png)

So for this issue will fix this up to position background on Shoes 4 the way it did back on Shoes 3.
