### ISSUE TITLE
Focus should focus

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#610]
I believe the following should show a highlighted button, and the button should get clicked whenever the user presses enter.

``` ruby
Shoes.app title: "Focus" do 
  stack do 
    b1 = button "This is a Button" 
    b1.focus() 
    b1.click {para "Ouch"} 
  end 
end
```

from: http://stackoverflow.com/questions/18298614/focus-in-ruby-shoes

**Comment by jasonrclark** [comment]
Tested this out currently on all three OSs, and Mac and Linux both properly highlight the button on startup for me, while Windows doesn't (the first control seems to get the focus).

Focus works right more actively later in the app... wonder if there's some odd timing things with SWT on Windows that we're hitting.

**Comment by jasonrclark** [comment]
Ok, I'm convinced, although I can't find other evidence online, that this is just an underlying SWT bug on Windows. It only happens when trying to set focus to a button that it won't work during startup. All the other element types gladly accept focus like you'd expect. Focus will also go gladly to buttons any other time after startup. :man_shrugging: 

Default button is a different thing (at least in Windows from back in my desktop C++ days... ah, the memoriSEGFAULT)

A workaround if you're having this problem is to set the focus like this instead:

```
timer 0.0 do
  really_important_button.focus
end
```

This gets the focus setting out into the main event loop which seems to dodge the bug.

Given the restricted scope and a workaround here, I'm gonna just close this out.
