### ISSUE TITLE
TextBlock#width should set width of text block

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#664]
Let's say I want to mono-space a mono-space font, by setting each character in its own little para with a fixed width. 
```ruby
Shoes.app do
  style(Shoes::Para, font: "Monospace 12px")
  s = "Here is some monospaced text"
  s.each_char do |char|
    para char, width: 10
  end
end
```

Instead of a flow of paras with a fixed width, I get a flow with a fixed width:

![weird](https://cloud.githubusercontent.com/assets/4992244/2781766/924d486a-cb17-11e3-90f3-551cf515c845.png)

There are probably better ways to monospace a mono-spaced font (kerning? shouldn't shoes monospace it?) but the bug stands!

**Comment by jasonrclark** [comment]
Between pre3 and pre4 something changed, and I'm seeing this now:

![image](https://cloud.githubusercontent.com/assets/130504/10413010/6f93b588-6f4f-11e5-9c80-0b02a468a4b5.png)

Actually have a little shoes-ing time, so probably look at this across the day or this evening. We all know how much I love text wrapping :grin:

**Comment by PragTob** [comment]
:+1: :rocket: 

![good luck](https://media.giphy.com/media/cYA2ClBxQZuiQ/giphy.gif)

**Comment by jasonrclark** [comment]
So got mostly to understanding what's needed here, but long weekend left me without enough energy to actually get it fully written out and tested.

Bottom line is there are two parts that need changing.  When we ask for the `[desired_width](https://github.com/shoes/shoes4/blob/master/shoes-core/lib/shoes/text_block_dimensions.rb#L33-L35)` for a text block, right now it's always squeezing our "desired" size by how far we've used up in the parent. If we have an explicit width set, though, we ought to ask for that width (as long as it fits in the parent's remaining space). This will allow the characters in the sample to actually attempt to take up the full width they're configured to want.

But that doesn't actually fix everything because the [text dimensions](https://github.com/shoes/shoes4/blob/master/shoes-swt/lib/shoes/swt/text_block.rb#L97-L98) interact with positioning to only advance as far as our actual text measures itself to. Again, in the unsized flowing case this is the right, but if we've asked for an explicit width (and it can be honored), then we ought to take that width.

Rough testing on this hacking the code appears to work right, but I want to tidy up how we represent the two states the text block can be in (size based on content vs size based on explicitly requested width). More to come in the next week!
