### ISSUE TITLE
Rename this repository to 'shoes'

### ISSUE THREAD

**Issue by wasnotrice** [shoes/shoes4#713]
As we near a release, I think it's appropriate to rename the repository currently know as 'shoes' to 'shoes3', and to rename this repository 'shoes'. Thoughts?

**Comment by jasonrclark** [comment]
Hmm, I have a hangup about this rename.

https://github.com/shoes/shoes has almost 200 forks, and many more stars than that. By doing a rename I'm pretty sure we're doing bad things to this git history of any of those existing clones. What happens when they pull? It either borks or they end up with totally different Shoes 4 stuff... neither seems worth it just for the naming gain.

I propose we stick with `shoes4`, and if we ever evolve past the 4.x line, we can consider a clever new rename at that point.

In the meantime, it might also be worth making the shoes/shoes README more strident about the fact that it's dead, and you should either be looking to shoes/shoes4 or Cecil's shoes3/shoes3 if you want something active.

What do you think @PragTob @wasnotrice ?

**Comment by ccoupe** [comment]
That old repo is a PITA, but as @jasonrclark  said, there are way too many forks and clones to dump it and  yet  a merge would be a waste of time.  A couple of Shoes3 contributers [have thoughts](https://github.com/Shoes3/shoes3/issues/377) about promoting Shoes, building community - yada yada not my skill set but I'm willing to follow a leader.

**Comment by jasonrclark** [comment]
Thanks for chiming in @ccoupe! Got a bit of graphic work [coming down the line for Shoes 4](https://github.com/shoes/shoes4/issues/1216#issuecomment-340661629) which I'm hoping to touch the website up with soon. Super happy to link to any and all Shoes communities that are out there!

Although I don't see the value in renaming other repos -> `shoes`, what about renaming `shoes` to `shoes-deprecated` with nothing in its place? GitHub will redirect so folks' links won't get broken, but for anyone new looking it'll give clear signal that shoes/shoes isn't the place they're looking for. We could also make a bold header in the README indicating you should go look elsewhere for help... we kinda bury that info a couple paragraphs down right now.

**Comment by ccoupe** [comment]
> Although I don't see the value in renaming other repos -> shoes, what about renaming shoes to shoes-deprecated

Seems like good idea to me. It might break  some things that probably need breaking (my repo's upstream but that is  part of the problem and mine to fix).

**Comment by jasonrclark** [comment]
At work (GitHub Enterprise vs public GitHub mind you), pushing to a renamed remote works perfectly fine. It gives a warning on the terminal that you're pushing to an out-of-date name is all. YMMV and I'm sure there's something out there that'd break, but at least that bit I expect to work.

**Comment by ccoupe** [comment]
If you can rename it, you might be able to rename it back, should it be problem some, no? I say (one voice) - try it.

**Comment by jasonrclark** [comment]
Poked the rename and futzed with the shoes/shoes README a bit. I was able to push/pull and git provided a warning that my remote name was out of date, but no further fuss.

@ccoupe don't know if you keep a pre-existing clone that you could pull from to see how it behaves for you?

**Comment by ccoupe** [comment]
I've got a shoes-1314 which pulls from  git://github.com/shoes/shoes except I've conflicts to  stash or commit before it completes. So, the old shoes/shoes is still available to that copy.

**Comment by jasonrclark** [comment]
🎉 I'm calling this done then. Thanks all!
