### ISSUE TITLE
Image with bad or relative file path

### ISSUE THREAD

**Issue by KCErb** [shoes/shoes4#826]
**Edit - rewrote question so that this doesn't partially become a duplicate of #292**

As noted [here](https://github.com/shoes/shoes4/pull/819#issue-39096262)
`image` should throw an error if it's given a bad file path, and it'd be nice if it would accept relative file paths as well.

This might go nicely with #292

**Comment by lumeet** [comment]
I've been doing some intial exploration of Shoes with this issues and had it pretty much done, when I noticed that the `file_path` argument in `Shoes::Image#initialize` may actually be image data. I don't know if it's only me but I found it somewhat confusing. :) So, what do you recommend, should I refactor `Shoes::Image#initialize` so that it has `file_path` and `data` (for instance) separately? Or should there be some detection logic for `file_path_or_data` instead? Or should I just keep my hands off of the code. ;)

**Comment by PragTob** [comment]
Hi there,

yes correctly noticed - maybe the code should be clearer there. Starting with a new argument name :-) This was a new feature/improvement as part of this pull request here: https://github.com/shoes/shoes4/pull/362

If detect logic is necessary then implement it, but I thought the code had some detection built in... would need to check that again.

Thanks for your work!

**Comment by PragTob** [comment]
Got you, the checking etc. is done on the backend side of things: https://github.com/shoes/shoes4/blob/master/shoes-swt/lib/shoes/swt/image.rb#L105-L107

It could be beneficiary to pull some of that up to the DSL level and do it already there. Not too sure but there is some code to check that on the backend/GUI - of course would be nice to reflect it on the DSL side of things as well. 

If you want you can also start with that, submit a pull request we check it out and go from there :-)

Thanks for contributing to shoes and happy new year!
Tobi

**Comment by lumeet** [comment]
Aah... sorry about that. It must have been the late disappoinment that made too lazy to be studious enough. :) Thanks for your guidance, I'll try have the time to submit a PR this week.
