### ISSUE TITLE
Slots probably need a backend representation

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#905]
Right now slots (stack/flow) just have a dummy backend representation without any effect - e.g. it doesn't really create an SWT element. We need a suitable SWT element that groups elements together but isn't actually displayed. 

Why do we probably need that?
- Scrolling #853
- Hiding all elements of a slot easily at once (without iterating through them and hiding each one of them, although that might not be the worst after all)

**Comment by KCErb** [comment]
I was looking at this in conjunction with #1036 and had some questions:

1. Why do we do all of the positioning for Flows and Slots in the front end? Feels like a backend thing. The front end says: hey here's some stuff that needs to flow, go ahead backend.

2. What suggestions do folks have as a suitable backend?

One thing that I see is a "Composite"

Here's the inheritance chain for a "composite" widget:

```
java.lang.Object
  org.eclipse.swt.widgets.Widget
    org.eclipse.swt.widgets.Control
      org.eclipse.swt.widgets.Scrollable
        org.eclipse.swt.widgets.Composite
```

So we could could choose what level of this queue we want for slots. "Control" for example has a setBounds which might be able to produce the desired effect of partially hiding contents.

I'm pretty green on the SWT side of this project so this *might* be a good place to dive in. Let me know what you guys think and if we can come up with a starting point I'll put in the time to code it up and see how we go from there.

**Comment by jasonrclark** [comment]
1. So in my mind, the big distinction between the DSL and backend layers is whether we'd want the logic shared or not. In the case of layout, I actually would want the same sizing of Flows and Stacks with elements to look the same across different backends. Given that, the DSL is the right place for the logic to live.

The backend really is more about the mechanics of turning your described UI into actual pixels on the screen, but ideally the DSL should have a precise picture of **what** you want drawn (sizing, etc.), regardless of backend.

2) I'm actually not too clear on the SWT side of this question either. I think that `Composite` is a very likely candidate. I remember it coming up with regards to scrolling (which has some similar concerns to this clipping I think).

A reasonable approach here might actually be to try wiring something up just using the `swt` gem directly to keep things simple while experimenting. I've got a raw SWT based JRuby app in a gist at https://gist.github.com/jasonrclark/a85f6c057d652c39a1f3 (YMMV, don't remember precisely what state of editing and tweaking it's in, but I've used it a few times when I wanted to fiddle with lower-level SWT stuff without having to wonder what Shoes was doing on top of it).

FWIW, I think the backend will have a large impact on the control-based elements like buttons and text boxes, but the painter-based elements (art elements, text) will probably be a whole other set of issues themselves since they draw directly to the graphics context.

**Comment by KCErb** [comment]
Hmm, OK, I'll try to start with something low level and see where things go.

**Comment by ccoupe** [comment]
I thought the back end was something that didn't require eval'ing Ruby code? In case somebody wanted to write a qt implementation of it, or wxWiindows or or or. For sure such a back end might have to call the rb_functions to define the classes and methods and parse method args but all the layout work was done in the front end DSL.  

Just my memory. YMMV.

**Comment by jasonrclark** [comment]
@ccoupe That may have been the case somewhere along the line, but as of now the Shoes 4 backend is entirely in Ruby since we have a JRuby binding to SWT. Any alternate backend will implement a Ruby-based API of classes and methods that the front-end talks to, although the internals could be entirely native if that makes sense given the UI library.

**Comment by PragTob** [comment]
Totally agree with @jasonrclark on 1.)

also not sure about 2.) and which composite element would be suitable. From memory I remember that I favored `Composite`. :)

I'm also not 100% sure if we're ready to tackle this yet. I mean, feel welcome to. For me it is still vague why/how we need a backend representation (beyond the scrolling, hiding I mentioned in the issue description).

So overall this is something that I'd tentatively put off a bit more until we have clearer view of what/why/how we need it.
