### ISSUE TITLE
require 'shoes' should figure out the backend to use

### ISSUE THREAD

**Issue by PragTob** [shoes/shoes4#933]
With shoes 4 we can also write scripts like:

```ruby
#!  /usr/bin/env jruby
require 'shoes'

Shoes.app do
  para 'ZOMG'
end
```

So people don't need to use the `shoes` executable but can just execute the scripte. If multiple backends are installed, we still need to pick the right one.

There is some of this code already there. I think we can do things like `Shoes.configuration.backend = :swt` - need to recheck that and then see what the behavior is with multiple backends.

@wasnotrice input on this one? :)

**Comment by jasonrclark** [comment]
I think this is actually already covered by @pjfitzgibbons' suggestion above--`bin/shoes` is smart enough to run our "picker" to decide on a backend, so the `require 'shoes'` doesn't need to get into the mix with that.

Confirmed locally that this works as expected with the following script (chmod'd to allow for executing and run outside the shoes4 directory to avoid getting local gems because of the Gemfile):

```
#!/usr/bin/env shoes

Shoes.app do
  para 'ZOMG'
end
```

Now this does require that someone run their script with the `shoes` executable, but I'm willing to live with that to avoid having our `shoes-core` requiring start invoking the picker itself in some fashion. If you agree @PragTob, shall we close this out?

**Comment by PragTob** [comment]
:+1:
